const cs = {
  settings_header: "Nastavení",
  logout: "Odhlásit se",
  logout_alert_title: "Odhlášeno",
  logout_alert_message: "Token byl smazán.",
  color_mode: "Barevný režim",
  sign_up: "Registrovat se",
  name_placeholder: "Jméno",
  email_placeholder: "E-mail",
  password_placeholder: "Heslo",
  password_again_placeholder: "Heslo znovu",
  passwords_not_match: "Hesla se neshodují",
  register_error: "Chyba registrace",
  signup_button: "Registrovat se",
  login_title: "Přihlášení",
  email: "E-mail",
  password: "Heslo",
  login_button: "Přihlásit se",
  register_redirect: "Vytvořit účet",
  dashboard_my_lists: "Moje ShopListy",
  dashboard_shared_lists: "Sdílené ShopListy",
  archive_header: "Archivované ShopListy",
  update_label: "Nové jméno:",
  update_confirm: "Potvrdit",
  update_cancel: "Zrušit",
  update_success: "Jméno bylo aktualizováno",
  update_success_mock: "Jméno bylo aktualizováno (mock)",
  update_error: "Chyba",
  loading_list: "Načítám seznam...",
  detail_title: "Detail seznamu: ",
  add_item: "+ Přidat položku",
  share_list: "Nadílet seznam",
  items_header: "Položky:",
  no_items: "Žádné položky",
  confirm_delete_title: "Opravdu chcete smazat?",
  yes: "Ano",
  no: "Ne",
  archived_done: "Hotovo",
  archived_text_archived: "ShopList archivován",
  archived_text_unarchived: "ShopList odstraněn z archivu",
  deleted_done: "Hotovo",
  deleted_text: "ShopList byl smazán",
  share_email_label: "Email:",
  share_placeholder: "Zadej email...",
  share_confirm: "Potvrdit",
  share_cancel: "Zrušit",
  share_success: "Seznam byl nasdílen.",
  share_user_not_found: "Uživatel s tímto emailem neexistuje.",
  share_already_shared: "Seznam je už nasdílen tomuto uživateli.",
  members_shared_with: "Sdíleno s:",
  members_loading: "Načítám členy…",
  members_none: "Žádní členové",
  members_remove_confirm: "Opravdu chcete odebrat {member}?",
  item_delete_confirm: 'Opravdu chcete smazat položku "{item}"?',
  shared_loading: "Načítám sdílené seznamy…",
  shared_empty: "Žádné sdílené seznamy",
  archived_loading: "Načítám archiv…",
  archived_empty: "Žádné archivované seznamy",
  dashboard_loading: "Načítám seznamy…",
  dashboard_empty: "Žádné vaše seznamy",
  createform_label: "Jméno nákupního seznamu:",
  createform_placeholder: "Zadej název...",
  createform_confirm: "Potvrdit",
  createform_cancel: "Zrušit",
  createform_success: "Seznam byl vytvořen",
  createform_error: "Chyba",
  additemform_label_name: "Jméno položky:",
  additemform_label_count: "Počet:",
  additemform_placeholder_name: "Zadej název...",
  additemform_confirm: "Potvrdit",
  additemform_cancel: "Zrušit",
  additemform_success: "Item byl přidán",
  additemform_success_mock: "Item byl přidán (mock)",
  additemform_error: "Chyba",
  additemform_invalid_count: "Počet musí být alespoň 1.",
  additemform_loading: "Načítám...",
   items_count: "Počet položek",
};

export default cs;
