const en = {
  settings_header: "Settings",
  logout: "Logout",
  logout_alert_title: "Logged out",
  logout_alert_message: "Token was removed.",
  color_mode: "Color mode",
  sign_up: "Sign Up",
  name_placeholder: "Name",
  email_placeholder: "E-mail",
  password_placeholder: "Password",
  password_again_placeholder: "Password again",
  passwords_not_match: "Passwords don't match",
  register_error: "Registration error",
  signup_button: "Sign Up",
  login_title: "Log in",
  email: "E-mail",
  password: "Password",
  login_button: "Log in",
  register_redirect: "Create account",
  dashboard_my_lists: "My ShopLists",
  dashboard_shared_lists: "Shared ShopLists",
  archive_header: "Archived ShopLists",
   update_label: "New name:",
  update_confirm: "Confirm",
  update_cancel: "Cancel",
  update_success: "Name updated",
  update_success_mock: "Name updated (mock)",
  update_error: "Error",
  loading_list: "Loading list...",
  detail_title: "List detail: ",
  add_item: "+ Add item",
  share_list: "Share list",
  items_header: "Items:",
  no_items: "No items",
  confirm_delete_title: "Are you sure you want to delete?",
  yes: "Yes",
  no: "No",
  archived_done: "Done",
  archived_text_archived: "ShopList archived",
  archived_text_unarchived: "ShopList removed from archive",
  deleted_done: "Done",
  deleted_text: "ShopList has been deleted",
  share_email_label: "Email:",
  share_placeholder: "Enter email...",
  share_confirm: "Confirm",
  share_cancel: "Cancel",
  share_success: "List has been shared.",
  share_user_not_found: "User with this email does not exist.",
  share_already_shared: "List is already shared with this user.",
  members_shared_with: "Shared with:",
  members_loading: "Loading members…",
  members_none: "No members",
  members_remove_confirm: "Do you really want to remove {member}?",
  item_delete_confirm: 'Do you really want to delete the item "{item}"?',
  shared_loading: "Loading shared lists…",
  shared_empty: "No shared lists",
  archived_loading: "Loading archived lists…",
  archived_empty: "No archived lists",
  dashboard_loading: "Loading your lists…",
  dashboard_empty: "No lists found",
  createform_label: "Shopping list name:",
  createform_placeholder: "Enter name...",
  createform_confirm: "Confirm",
  createform_cancel: "Cancel",
  createform_success: "List created successfully",
  createform_error: "Error",
  additemform_label_name: "Item name:",
  additemform_label_count: "Count:",
  additemform_placeholder_name: "Enter name...",
  additemform_confirm: "Confirm",
  additemform_cancel: "Cancel",
  additemform_success: "Item added",
  additemform_success_mock: "Item added (mock)",
  additemform_error: "Error",
  additemform_invalid_count: "Count must be at least 1.",
  additemform_loading: "Loading...",
   items_count: "Items count",

};

export default en;
